export const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

export const GROQ_MODEL_FAST = 'llama-3.1-8b-instant'
export const GROQ_MODEL_SMART = 'llama-3.3-70b-versatile'

/**
 * Standardizes error reporting. Hides raw system exceptions from the user
 * but logs full details to the edge function server logs.
 */
export function sanitizeError(err: Error, context = ''): { error: string; details?: string } {
  console.error(`[AI Engine Failure] Context: ${context} | Error: ${err.message}\nStack: ${err.stack}`)
  
  let friendlyMessage = 'An AI-related service error occurred. The operation could not be completed.'
  if (err.message.includes('rate limit') || err.message.includes('429')) {
    friendlyMessage = 'The AI service is currently overloaded. Please try again in a moment.'
  } else if (err.message.includes('JSON parse') || err.message.includes('validation')) {
    friendlyMessage = 'Failed to validate the AI response. Please try again.'
  } else if (err.message.includes('fallback chain')) {
    friendlyMessage = 'All AI engine providers are currently unreachable. Please try again later.'
  }
  
  return { error: friendlyMessage }
}

/**
 * Strips markdown code fences from JSON strings.
 */
export function stripJson(raw: string): string {
  return raw
    .replace(/^```json\s*/i, '')
    .replace(/^```\s*/i, '')
    .replace(/```\s*$/i, '')
    .trim()
}

/**
 * Automatically repairs common JSON defects generated by LLMs
 * (e.g. trailing commas, missing closing brackets).
 */
export function repairJson(raw: string): string {
  let cleaned = stripJson(raw)
  
  // Remove trailing commas in JSON arrays/objects: ,} -> } and ,] -> ]
  cleaned = cleaned.replace(/,\s*([}\]])/g, '$1')
  
  // Balance curly braces
  const openBraces = (cleaned.match(/{/g) || []).length
  const closeBraces = (cleaned.match(/}/g) || []).length
  if (openBraces > closeBraces) {
    cleaned += '}'.repeat(openBraces - closeBraces)
  }
  
  // Balance square brackets
  const openBrackets = (cleaned.match(/\[/g) || []).length
  const closeBrackets = (cleaned.match(/\]/g) || []).length
  if (openBrackets > closeBrackets) {
    cleaned += ']'.repeat(openBrackets - closeBrackets)
  }
  
  return cleaned
}

export interface AiMessage {
  role: string
  content: string | null
  tool_calls?: any[]
}

/**
 * Full message completion call returning the message object with optional tool_calls.
 */
export async function callAiMessageWithFallback(opts: {
  messages: Array<{ role: string; content: any }>
  temperature?: number
  maxTokens?: number
  modelOverride?: string
  tools?: any[] | null
}): Promise<AiMessage> {
  const {
    messages,
    temperature = 0.7,
    maxTokens = 1024,
    modelOverride,
    tools = null
  } = opts

  const startTime = Date.now()

  // 1. Attempt Primary: Groq
  const groqKey = Deno.env.get('GROQ_API_KEY')
  if (groqKey) {
    const model = modelOverride || GROQ_MODEL_SMART
    try {
      console.log(`[AI-Chain] Attempting Groq (${model})`)
      const body: any = {
        model,
        messages,
        temperature,
        max_tokens: maxTokens,
      }
      if (tools && tools.length > 0) body.tools = tools

      const resp = await fetch('https://api.groq.com/openai/v1/chat/completions', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${groqKey}`,
        },
        body: JSON.stringify(body),
      })
      if (resp.ok) {
        const data = await resp.json()
        const message = data.choices?.[0]?.message
        if (message) {
          console.log(`[AI-Chain] Groq success in ${Date.now() - startTime}ms`)
          return message
        }
      } else {
        const errText = await resp.text()
        console.warn(`[AI-Chain] Groq HTTP error ${resp.status}: ${errText.slice(0, 200)}`)
      }
    } catch (e: any) {
      console.warn(`[AI-Chain] Groq exception: ${e.message}`)
    }
  }

  // 2. Attempt Secondary: OpenAI
  const openAiKey = Deno.env.get('OPENAI_API_KEY')
  if (openAiKey) {
    const model = modelOverride?.includes('vision') ? 'gpt-4o-mini' : 'gpt-4o-mini'
    try {
      console.log(`[AI-Chain] Falling back to OpenAI (${model})`)
      const body: any = {
        model,
        messages,
        temperature,
        max_tokens: maxTokens,
      }
      if (tools && tools.length > 0) body.tools = tools

      const resp = await fetch('https://api.openai.com/v1/chat/completions', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${openAiKey}`,
        },
        body: JSON.stringify(body),
      })
      if (resp.ok) {
        const data = await resp.json()
        const message = data.choices?.[0]?.message
        if (message) {
          console.log(`[AI-Chain] OpenAI success in ${Date.now() - startTime}ms`)
          return message
        }
      } else {
        const errText = await resp.text()
        console.warn(`[AI-Chain] OpenAI HTTP error ${resp.status}: ${errText.slice(0, 200)}`)
      }
    } catch (e: any) {
      console.warn(`[AI-Chain] OpenAI exception: ${e.message}`)
    }
  }

  // 3. Attempt Tertiary: Gemini
  const geminiKey = Deno.env.get('GEMINI_API_KEY') || Deno.env.get('GOOGLE_API_KEY')
  if (geminiKey) {
    try {
      console.log('[AI-Chain] Falling back to Gemini (gemini-1.5-flash)')
      
      // Adapt messages array to Gemini contents structure
      const geminiContents = messages.map(msg => {
        let parts = []
        if (Array.isArray(msg.content)) {
          parts = msg.content.map(part => {
            if (part.type === 'text') {
              return { text: part.text }
            } else if (part.type === 'image_url' && part.image_url?.url) {
              const matches = part.image_url.url.match(/^data:(image\/\w+);base64,(.+)$/)
              if (matches) {
                return {
                  inlineData: {
                    mimeType: matches[1],
                    data: matches[2]
                  }
                }
              }
            }
            return { text: JSON.stringify(part) }
          })
        } else {
          parts = [{ text: String(msg.content) }]
        }
        
        return {
          role: msg.role === 'assistant' ? 'model' : 'user',
          parts
        }
      })

      const systemInstruction = messages.find(m => m.role === 'system')?.content
      const filteredContents = geminiContents.filter(c => c.role !== 'system')

      const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${geminiKey}`
      const body: any = { contents: filteredContents }
      if (systemInstruction) {
        body.systemInstruction = { parts: [{ text: String(systemInstruction) }] }
      }
      
      // Map tools to Gemini schema if provided (Gemini handles function calling as well)
      if (tools && tools.length > 0) {
        body.tools = [{
          functionDeclarations: tools.map(t => ({
            name: t.function.name,
            description: t.function.description,
            parameters: t.function.parameters
          }))
        }]
      }

      body.generationConfig = {
        temperature,
        maxOutputTokens: maxTokens,
      }

      const resp = await fetch(url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
      })

      if (resp.ok) {
        const data = await resp.json()
        const candidate = data.candidates?.[0]
        const geminiContent = candidate?.content?.parts?.[0]?.text
        const functionCalls = candidate?.content?.parts?.filter((p: any) => p.functionCall)

        if (functionCalls && functionCalls.length > 0) {
          // Map Gemini function call back to OpenAI tool_calls format
          const toolCalls = functionCalls.map((fc: any, index: number) => ({
            id: `call_${fc.functionCall.name}_${index}`,
            type: 'function',
            function: {
              name: fc.functionCall.name,
              arguments: JSON.stringify(fc.functionCall.args)
            }
          }))
          console.log(`[AI-Chain] Gemini success (tool use) in ${Date.now() - startTime}ms`)
          return {
            role: 'assistant',
            content: geminiContent || null,
            tool_calls: toolCalls
          }
        }

        if (geminiContent !== undefined) {
          console.log(`[AI-Chain] Gemini success in ${Date.now() - startTime}ms`)
          return {
            role: 'assistant',
            content: geminiContent
          }
        }
      } else {
        const errText = await resp.text()
        console.warn(`[AI-Chain] Gemini HTTP error ${resp.status}: ${errText.slice(0, 200)}`)
      }
    } catch (e: any) {
      console.warn(`[AI-Chain] Gemini exception: ${e.message}`)
    }
  }

  throw new Error('All model API endpoints in the fallback chain failed or were unconfigured.')
}

/**
 * Standard content completion call returning raw string.
 */
export async function callAiWithFallback(opts: {
  messages: Array<{ role: string; content: any }>
  temperature?: number
  maxTokens?: number
  modelOverride?: string
}): Promise<string> {
  const message = await callAiMessageWithFallback(opts)
  return message.content || ''
}

/**
 * Drop-in wrapper for legacy code importing callGroq.
 */
export async function callGroq(opts: {
  apiKey: string
  model?: string
  prompt: string
  temperature?: number
  maxTokens?: number
}): Promise<string> {
  return callAiWithFallback({
    messages: [{ role: 'user', content: opts.prompt }],
    temperature: opts.temperature,
    maxTokens: opts.maxTokens,
    modelOverride: opts.model
  })
}
