
import { User, Post, Story, Event, MarketItem, Confession, StudyGroup, Conversation, Notification, CourseThread, Reel, Highlight, Comment } from './types';

export const CURRENT_USER: User = {
  id: 'u1',
  username: 'alex_codes',
  fullName: 'Alex Johnson',
  avatar: 'https://picsum.photos/seed/alex/200',
  coverImage: 'https://picsum.photos/seed/alexcover/800/300',
  university: 'Stanford University',
  major: 'Computer Science',
  year: 2026,
  bio: 'Building the future, one commit at a time 💻✨ | CS @ Stanford | AI enthusiast',
  verified: true,
  verificationType: 'student',
  interests: ['Coding', 'AI', 'Basketball', 'Jazz'],
  followers: 1240,
  following: 318,
  posts: 47,
  website: 'alexjohnson.dev',
  pronouns: 'he/him',
};

export const MOCK_USERS: User[] = [
  {
    id: 'u2',
    username: 'sarah_bio',
    fullName: 'Sarah Miller',
    avatar: 'https://picsum.photos/seed/sarah/200',
    coverImage: 'https://picsum.photos/seed/sarahcover/800/300',
    university: 'Stanford University',
    major: 'Biology',
    year: 2025,
    bio: 'Plant mom & aspiring doctor 🌿 | Pre-med | Research @ Hopkins Lab',
    verified: true,
    verificationType: 'student',
    interests: ['Botany', 'Medicine', 'Hiking'],
    followers: 892,
    following: 210,
    posts: 63,
  },
  {
    id: 'u3',
    username: 'stanford_cs_club',
    fullName: 'Stanford CS Society',
    avatar: 'https://picsum.photos/seed/club/200',
    coverImage: 'https://picsum.photos/seed/clubcover/800/300',
    university: 'Stanford University',
    major: 'Club',
    year: 2024,
    bio: 'Official Stanford CS Club | Hackathons • Workshops • Networking 🚀',
    verified: true,
    verificationType: 'club',
    isClub: true,
    interests: ['Technology', 'Programming', 'Networking'],
    followers: 4320,
    following: 88,
    posts: 212,
  },
  {
    id: 'u4',
    username: 'prof_chen',
    fullName: 'Dr. Linda Chen',
    avatar: 'https://picsum.photos/seed/profchen/200',
    university: 'Stanford University',
    major: 'Professor - Machine Learning',
    year: 2000,
    bio: 'ML Research @ Stanford AI Lab | Author of "Deep Learning Fundamentals" | PhD MIT',
    verified: true,
    verificationType: 'professor',
    interests: ['Machine Learning', 'Research', 'Education'],
    followers: 12800,
    following: 142,
    posts: 330,
  },
  {
    id: 'u5',
    username: 'marcus_hoop',
    fullName: 'Marcus Thompson',
    avatar: 'https://picsum.photos/seed/marcus/200',
    university: 'Stanford University',
    major: 'Sports Science',
    year: 2026,
    bio: 'Stanford Basketball #24 🏀 | Sports Science | Future NBA | God First',
    verified: true,
    verificationType: 'influencer',
    interests: ['Basketball', 'Fitness', 'Music'],
    followers: 38700,
    following: 521,
    posts: 145,
  },
  {
    id: 'u6',
    username: 'priya_design',
    fullName: 'Priya Sharma',
    avatar: 'https://picsum.photos/seed/priya/200',
    university: 'Stanford University',
    major: 'Human-Computer Interaction',
    year: 2025,
    bio: 'UI/UX designer | Creating beautiful things ✨ | prev @Google intern',
    verified: false,
    interests: ['Design', 'Art', 'Travel'],
    followers: 2100,
    following: 430,
    posts: 89,
  },
  {
    id: 'u7',
    username: 'jay_econ',
    fullName: 'James Carter',
    avatar: 'https://picsum.photos/seed/james/200',
    university: 'Stanford University',
    major: 'Economics',
    year: 2024,
    bio: 'Econ nerd 📊 | Trading | VC-bound | Startup founder @UniMarket',
    verified: false,
    interests: ['Finance', 'Startups', 'Chess'],
    followers: 450,
    following: 312,
    posts: 34,
  },
];

const MOCK_COMMENTS: Comment[] = [
  {
    id: 'cm1',
    userId: 'u4',
    user: MOCK_USERS[2],
    text: 'This is amazing! Keep up the great work 🔥',
    likes: 42,
    timestamp: '1h ago',
    replies: [
      {
        id: 'cm1r1',
        userId: 'u2',
        user: MOCK_USERS[0],
        text: 'Thank you so much!! 🙏',
        likes: 12,
        timestamp: '45m ago',
      }
    ]
  },
  {
    id: 'cm2',
    userId: 'u5',
    user: MOCK_USERS[3],
    text: 'Congrats! Late nights pay off 💪',
    likes: 18,
    timestamp: '30m ago',
  },
  {
    id: 'cm3',
    userId: 'u6',
    user: MOCK_USERS[4],
    text: 'The design is so clean omg 😍',
    likes: 9,
    timestamp: '15m ago',
  },
];

export const MOCK_POSTS: Post[] = [
  {
    id: 'p1',
    userId: 'u2',
    user: MOCK_USERS[0],
    type: 'image',
    mediaUrl: 'https://picsum.photos/seed/post1/600/600',
    caption: 'Late night study sessions at the main library. Finals are coming! 📚☕️ The grind never stops. Who else is cramming? Drop a 📚 below!',
    likes: 124,
    comments: 18,
    reposts: 7,
    saves: 34,
    timestamp: '2h ago',
    universityTag: 'Stanford University',
    hashtags: ['#StanfordLife', '#Finals', '#StudyVibes'],
    commentList: MOCK_COMMENTS,
  },
  {
    id: 'p2',
    userId: 'u3',
    user: MOCK_USERS[1],
    type: 'image',
    mediaUrl: 'https://picsum.photos/seed/post2/600/600',
    caption: 'Hackathon winners announced! Congrats to Team Apollo for their amazing AI health app. 🏆✨ What an incredible weekend of building!',
    likes: 450,
    comments: 32,
    reposts: 89,
    saves: 112,
    timestamp: '5h ago',
    universityTag: 'Stanford University',
    hashtags: ['#Hackathon2024', '#AI', '#Stanford'],
    commentList: MOCK_COMMENTS.slice(0, 2),
  },
  {
    id: 'p3',
    userId: 'u4',
    user: MOCK_USERS[2],
    type: 'thread',
    caption: 'Hot take: Most CS students spend too much time on LeetCode and not enough time building real projects. Your GitHub matters more than your LeetCode stats to most companies now. Thoughts? 🧵',
    likes: 892,
    comments: 145,
    reposts: 234,
    saves: 67,
    timestamp: '8h ago',
    hashtags: ['#TechTalk', '#CS', '#CareerAdvice'],
    commentList: MOCK_COMMENTS,
  },
  {
    id: 'p4',
    userId: 'u5',
    user: MOCK_USERS[3],
    type: 'image',
    mediaUrl: 'https://picsum.photos/seed/basketball/600/600',
    caption: 'Pre-game warmup. Season opener this Friday 🏀🔥 Come through to the arena! Tickets in bio. Let\'s fill those stands Stanford! #CardinalBasketball',
    likes: 4210,
    comments: 312,
    reposts: 567,
    saves: 890,
    timestamp: '12h ago',
    hashtags: ['#CardinalBasketball', '#Stanford', '#NCAA'],
    views: 48200,
  },
  {
    id: 'p5',
    userId: 'u6',
    user: MOCK_USERS[4],
    type: 'image',
    mediaUrl: 'https://picsum.photos/seed/design/600/600',
    caption: 'Redesigned the campus app navigation. What do you think? Swipe for before/after! 🎨✨ DM if you want a critique of your UI',
    likes: 1820,
    comments: 94,
    reposts: 143,
    saves: 451,
    timestamp: '1d ago',
    hashtags: ['#UIDesign', '#UX', '#DesignThinking'],
    commentList: MOCK_COMMENTS.slice(1),
  },
  {
    id: 'p6',
    userId: 'u7',
    user: MOCK_USERS[5],
    type: 'thread',
    caption: 'THREAD: How I turned $500 savings into $4,200 in 6 months trading ETFs as a college student (without touching crypto). A breakdown 👇',
    likes: 2340,
    comments: 289,
    reposts: 891,
    saves: 1240,
    timestamp: '2d ago',
    hashtags: ['#Finance', '#Investing', '#CollegeMoney'],
  },
];

export const MOCK_STORIES: Story[] = [
  { id: 's1', userId: 'u1', user: CURRENT_USER, mediaUrl: 'https://picsum.photos/seed/s1/400/700', timestamp: '1h ago', viewed: false },
  { id: 's2', userId: 'u2', user: MOCK_USERS[0], mediaUrl: 'https://picsum.photos/seed/s2/400/700', timestamp: '3h ago', caption: 'Library vibes 📚', viewed: false },
  { id: 's3', userId: 'u3', user: MOCK_USERS[1], mediaUrl: 'https://picsum.photos/seed/s3/400/700', timestamp: '5h ago', caption: 'Hackathon recap!', viewed: false },
  { id: 's4', userId: 'u5', user: MOCK_USERS[3], mediaUrl: 'https://picsum.photos/seed/s5/400/700', timestamp: '6h ago', caption: 'Practice day 🏀', viewed: true },
  { id: 's5', userId: 'u6', user: MOCK_USERS[4], mediaUrl: 'https://picsum.photos/seed/s6/400/700', timestamp: '8h ago', caption: 'New design drop', viewed: true },
  { id: 's6', userId: 'u4', user: MOCK_USERS[2], mediaUrl: 'https://picsum.photos/seed/s7/400/700', timestamp: '10h ago', caption: 'Office hours today', viewed: true },
];

export const MOCK_EVENTS: Event[] = [
  {
    id: 'e1',
    title: 'Spring Tech Symposium',
    description: 'A deep dive into Web3 and AI architectures. Featuring speakers from Google, Meta, and top startups.',
    date: 'Apr 15, 2026',
    time: '2:00 PM',
    location: 'Gates Computer Science Building',
    organizer: MOCK_USERS[1],
    attendees: 156,
    image: 'https://picsum.photos/seed/e1/600/300',
    category: 'Academic',
    isPromoted: true,
    price: 'free',
    maxAttendees: 200,
    tags: ['AI', 'Web3', 'Networking'],
  },
  {
    id: 'e2',
    title: 'Campus Musical Night',
    description: 'Featuring the university jazz band and local artists. Food and drinks included!',
    date: 'Apr 20, 2026',
    time: '7:00 PM',
    location: 'Memorial Auditorium',
    organizer: MOCK_USERS[0],
    attendees: 340,
    image: 'https://picsum.photos/seed/e2/600/300',
    category: 'Social',
    price: 10,
    maxAttendees: 500,
    tags: ['Music', 'Jazz', 'Social'],
  },
  {
    id: 'e3',
    title: 'Career Fair: FinTech',
    description: 'Meet top recruiters from leading fintech companies. Bring your resume!',
    date: 'Apr 22, 2026',
    time: '10:00 AM',
    location: 'Student Union Hall',
    organizer: MOCK_USERS[2],
    attendees: 89,
    image: 'https://picsum.photos/seed/e3/600/300',
    category: 'Career',
    price: 'free',
    tags: ['Career', 'Finance', 'Recruiting'],
  },
  {
    id: 'e4',
    title: 'Intramural Basketball Tournament',
    description: '3v3 and 5v5 brackets. Register your team now. Prizes for top 3 teams!',
    date: 'Apr 27, 2026',
    time: '9:00 AM',
    location: 'Maples Pavilion',
    organizer: MOCK_USERS[3],
    attendees: 210,
    image: 'https://picsum.photos/seed/e4/600/300',
    category: 'Sports',
    price: 5,
    tags: ['Basketball', 'Sports', 'Tournament'],
  },
  {
    id: 'e5',
    title: 'UI/UX Design Workshop',
    description: 'Hands-on Figma workshop for beginners and intermediate designers.',
    date: 'May 3, 2026',
    time: '3:00 PM',
    location: 'd.school Innovation Hub',
    organizer: MOCK_USERS[4],
    attendees: 45,
    image: 'https://picsum.photos/seed/e5/600/300',
    category: 'Workshop',
    price: 'free',
    maxAttendees: 60,
    tags: ['Design', 'Figma', 'Workshop'],
  },
];

export const MOCK_STUDY_GROUPS: StudyGroup[] = [
  { id: 'g1', name: 'Algorithm Masters', courseCode: 'CS106B', members: 12, description: 'Practice for technical interviews and DSA deep dives.', isJoined: true, nextMeeting: 'Tomorrow 6pm' },
  { id: 'g2', name: 'Bio Med Study Circle', courseCode: 'BIO200', members: 8, description: 'Weekly review of lab sessions and exam prep.', isJoined: false },
  { id: 'g3', name: 'ML Study Group', courseCode: 'CS229', members: 23, description: 'Work through Stanford ML course problem sets together.', isJoined: true, nextMeeting: 'Fri 4pm' },
  { id: 'g4', name: 'Econ Study Hall', courseCode: 'ECON102', members: 15, description: 'Game theory and macro deep dives.', isJoined: false },
];

export const MOCK_MARKET: MarketItem[] = [
  {
    id: 'm1',
    title: 'Cracking the Coding Interview - 6th Ed',
    price: 25,
    image: 'https://picsum.photos/seed/m1/400/400',
    category: 'books',
    seller: CURRENT_USER,
    description: 'Barely used, all pages intact. Perfect for SWE interview prep.',
    condition: 'like-new',
    postedAt: '2d ago',
  },
  {
    id: 'm2',
    title: 'Dell 27" 4K Monitor',
    price: 180,
    image: 'https://picsum.photos/seed/m2/400/400',
    category: 'gadgets',
    seller: MOCK_USERS[0],
    description: 'Great condition, minor cosmetic scratches. Comes with cable.',
    condition: 'good',
    postedAt: '1d ago',
  },
  {
    id: 'm3',
    title: 'Single Room Sublease - Summer 2026',
    price: 1200,
    image: 'https://picsum.photos/seed/m3/400/400',
    category: 'housing',
    seller: MOCK_USERS[5],
    description: 'Furnished single room near campus. Available June-Aug.',
    condition: 'good',
    postedAt: '3h ago',
  },
  {
    id: 'm4',
    title: 'CS229 Full Notes Bundle',
    price: 15,
    image: 'https://picsum.photos/seed/m4/400/400',
    category: 'notes',
    seller: MOCK_USERS[1],
    description: 'Complete typed notes + problem set solutions. A+ student.',
    condition: 'new',
    postedAt: '5h ago',
  },
  {
    id: 'm5',
    title: 'Nike Air Force 1 Size 10',
    price: 65,
    image: 'https://picsum.photos/seed/m5/400/400',
    category: 'clothing',
    seller: MOCK_USERS[3],
    description: 'Lightly worn, very clean. Will negotiate.',
    condition: 'good',
    postedAt: '1h ago',
  },
  {
    id: 'm6',
    title: 'IKEA Study Desk + Chair',
    price: 80,
    image: 'https://picsum.photos/seed/m6/400/400',
    category: 'furniture',
    seller: MOCK_USERS[2],
    description: 'Moving out sale. Full desk set, great condition.',
    condition: 'good',
    postedAt: '6h ago',
  },
];

export const MOCK_CONFESSIONS: Confession[] = [
  { id: 'c1', text: "I still don't know where the psychology building is and I've been here for 3 years. I just Google Maps it every time.", likes: 892, timestamp: '1h ago', replies: 34 },
  { id: 'c2', text: "The coffee at the library is actually better than the one at the student union, change my mind.", likes: 445, timestamp: '4h ago', replies: 67 },
  { id: 'c3', text: "I've been copy-pasting from my own old assignments and calling it 'referencing prior work'. I'm not stopping.", likes: 1240, timestamp: '6h ago', replies: 89 },
  { id: 'c4', text: "Lowkey have a crush on someone in my CS class but I'm too scared to DM them on UniGram 👀 they're in this app rn probably", likes: 2301, timestamp: '8h ago', replies: 145 },
  { id: 'c5', text: "I eat at the dining hall alone every day and honestly? I prefer it. Podcasts + good food = perfect lunch.", likes: 678, timestamp: '10h ago', replies: 23 },
  { id: 'c6', text: "Got into Stanford off the waitlist and still feel like an imposter every single day. Nobody talks about this.", likes: 3450, timestamp: '12h ago', replies: 234 },
  { id: 'c7', text: "My study group literally carries me every exam and I contribute almost nothing. They think I'm smart. I'm not. I'm just good at nodding.", likes: 1890, timestamp: '1d ago', replies: 112 },
];

export const MOCK_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv1',
    participants: [MOCK_USERS[0]],
    lastMessage: { id: 'msg1', senderId: 'u2', text: 'Hey!! Did you see the hackathon results? 🎉', timestamp: '2m ago', read: false },
    unreadCount: 3,
  },
  {
    id: 'conv2',
    participants: [MOCK_USERS[1]],
    lastMessage: { id: 'msg2', senderId: 'u3', text: 'CS Club meeting tomorrow at 6pm, don\'t forget!', timestamp: '1h ago', read: false },
    unreadCount: 1,
  },
  {
    id: 'conv3',
    participants: [MOCK_USERS[3]],
    lastMessage: { id: 'msg3', senderId: 'u5', text: 'Gym at 7am? 💪', timestamp: '3h ago', read: true },
    unreadCount: 0,
  },
  {
    id: 'conv4',
    participants: [MOCK_USERS[2]],
    lastMessage: { id: 'msg4', senderId: 'u4', text: 'Office hours are moved to Thursday this week.', timestamp: '1d ago', read: true },
    unreadCount: 0,
  },
  {
    id: 'conv5',
    participants: [MOCK_USERS[4], MOCK_USERS[5]],
    lastMessage: { id: 'msg5', senderId: 'u6', text: 'Anyone want to work on the project tonight?', timestamp: '2d ago', read: true },
    unreadCount: 0,
    isGroup: true,
    groupName: 'HCI Project Group',
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  { id: 'n1', type: 'like', user: MOCK_USERS[3], text: 'liked your post', timestamp: '2m ago', read: false, postImage: 'https://picsum.photos/seed/post1/100' },
  { id: 'n2', type: 'follow', user: MOCK_USERS[0], text: 'started following you', timestamp: '15m ago', read: false },
  { id: 'n3', type: 'comment', user: MOCK_USERS[2], text: 'commented: "This is amazing! Keep up the great work 🔥"', timestamp: '1h ago', read: false, postImage: 'https://picsum.photos/seed/post2/100' },
  { id: 'n4', type: 'repost', user: MOCK_USERS[1], text: 'reposted your thread', timestamp: '2h ago', read: false },
  { id: 'n5', type: 'mention', user: MOCK_USERS[4], text: 'mentioned you in a comment', timestamp: '3h ago', read: true, postImage: 'https://picsum.photos/seed/design/100' },
  { id: 'n6', type: 'verification', user: MOCK_USERS[1], text: 'Your verification application is under review ✅', timestamp: '1d ago', read: true },
  { id: 'n7', type: 'event', user: MOCK_USERS[1], text: 'Spring Tech Symposium is tomorrow! Don\'t forget to attend', timestamp: '1d ago', read: true },
  { id: 'n8', type: 'like', user: MOCK_USERS[5], text: 'and 47 others liked your post', timestamp: '2d ago', read: true, postImage: 'https://picsum.photos/seed/post1/100' },
];

export const MOCK_COURSES: CourseThread[] = [
  { id: 'ct1', courseCode: 'CS106B', courseName: 'Programming Abstractions', posts: 234, members: 189, isJoined: true, department: 'Computer Science', professor: 'Prof. Zelenski', color: 'indigo' },
  { id: 'ct2', courseCode: 'CS229', courseName: 'Machine Learning', posts: 456, members: 312, isJoined: true, department: 'Computer Science', professor: 'Dr. Linda Chen', color: 'purple' },
  { id: 'ct3', courseCode: 'ECON102', courseName: 'Principles of Macroeconomics', posts: 123, members: 445, isJoined: false, department: 'Economics', professor: 'Prof. Summers', color: 'green' },
  { id: 'ct4', courseCode: 'BIO200', courseName: 'Cell Biology', posts: 89, members: 267, isJoined: false, department: 'Biology', color: 'yellow' },
  { id: 'ct5', courseCode: 'HCI247', courseName: 'Human-Computer Interaction', posts: 178, members: 134, isJoined: true, department: 'HCI', professor: 'Prof. Klemmer', color: 'pink' },
  { id: 'ct6', courseCode: 'MATH108', courseName: 'Introduction to Combinatorics', posts: 67, members: 98, isJoined: false, department: 'Mathematics', color: 'orange' },
];

export const MOCK_REELS: Reel[] = [
  {
    id: 'r1',
    user: MOCK_USERS[3],
    videoUrl: '',
    thumbnail: 'https://picsum.photos/seed/reel1/400/700',
    caption: 'Pre-game drills 🏀🔥 Season opener this Friday!! #CardinalNation #Basketball',
    likes: 8420,
    comments: 234,
    shares: 567,
    timestamp: '3h ago',
    song: 'Rich Flex - Drake & 21 Savage',
    duration: 28,
    views: 92300,
  },
  {
    id: 'r2',
    user: MOCK_USERS[4],
    videoUrl: '',
    thumbnail: 'https://picsum.photos/seed/reel2/400/700',
    caption: 'Campus at golden hour never gets old 🌅 Stanford is just different fr #CampusLife',
    likes: 3210,
    comments: 89,
    shares: 123,
    timestamp: '6h ago',
    song: 'Golden Hour - JVKE',
    duration: 15,
    views: 41000,
  },
  {
    id: 'r3',
    user: MOCK_USERS[1],
    videoUrl: '',
    thumbnail: 'https://picsum.photos/seed/reel3/400/700',
    caption: 'Hackathon day 2 energy ⚡ 36 hours in and we\'re still COOKING #HackStanford2024',
    likes: 5670,
    comments: 312,
    shares: 234,
    timestamp: '1d ago',
    song: 'HUMBLE - Kendrick Lamar',
    duration: 22,
    views: 67800,
  },
  {
    id: 'r4',
    user: MOCK_USERS[0],
    videoUrl: '',
    thumbnail: 'https://picsum.photos/seed/reel4/400/700',
    caption: 'Study aesthetic for finals week 📚✨ POV: You have 4 exams in 3 days. Sending strength.',
    likes: 12400,
    comments: 678,
    shares: 1230,
    timestamp: '2d ago',
    song: 'lofi beats - ChillHop',
    duration: 30,
    views: 234000,
  },
];

export const TRENDING_HASHTAGS = [
  { tag: '#StanfordLife', posts: '12.4K' },
  { tag: '#HackStanford2024', posts: '8.9K' },
  { tag: '#Finals', posts: '34.2K' },
  { tag: '#CampusLife', posts: '89.1K' },
  { tag: '#CardinalBasketball', posts: '5.6K' },
  { tag: '#StudyVibes', posts: '21.3K' },
  { tag: '#PreMed', posts: '7.8K' },
  { tag: '#TechTalk', posts: '15.2K' },
  { tag: '#CampusEats', posts: '9.4K' },
  { tag: '#CollegeMoney', posts: '18.7K' },
];

export const SUGGESTED_USERS: User[] = [MOCK_USERS[3], MOCK_USERS[4], MOCK_USERS[2]];
