import React, { useState } from 'react';
import { View, Text, TouchableOpacity, StyleSheet } from 'react-native';
import { Ionicons } from '@expo/vector-icons';

export type AIContextType = 'none' | 'info' | 'warning' | 'misleading';

export interface AIContextResult {
  type: AIContextType;
  context: string;
  detail: string;
  confidence: number;
}

const CONFIG = {
  info: {
    icon: 'information-circle-outline' as const,
    label: 'AI Context',
    border: '#3b82f6',
    lightBg: '#eff6ff',
    darkBg: '#172554',
    lightText: '#1d4ed8',
    darkText: '#93c5fd',
  },
  warning: {
    icon: 'warning-outline' as const,
    label: 'Unverified Claim',
    border: '#f59e0b',
    lightBg: '#fffbeb',
    darkBg: '#3d2a00',
    lightText: '#92400e',
    darkText: '#fcd34d',
  },
  misleading: {
    icon: 'alert-circle-outline' as const,
    label: 'Misleading Info',
    border: '#ef4444',
    lightBg: '#fff1f2',
    darkBg: '#3b0a0a',
    lightText: '#991b1b',
    darkText: '#fca5a5',
  },
};

interface Props {
  result: AIContextResult;
  isDark: boolean;
}

// [Abena Owusu - Frontend Dev] React.memo: AI card renders inside explore scroll, skip re-renders on unrelated state
export const AIContextCard: React.FC<Props> = React.memo(({ result, isDark }) => {
  const [expanded, setExpanded] = useState(false);

  if (result.type === 'none') return null;

  const cfg = CONFIG[result.type];
  const bg = isDark ? cfg.darkBg : cfg.lightBg;
  const textColor = isDark ? cfg.darkText : cfg.lightText;

  return (
    <TouchableOpacity
      activeOpacity={0.85}
      onPress={() => setExpanded(e => !e)}
      style={[styles.card, { backgroundColor: bg, borderLeftColor: cfg.border }]}
    >
      <View style={styles.row}>
        <View style={styles.rowLeft}>
          <Ionicons name={cfg.icon} size={14} color={cfg.border} />
          <Text style={[styles.label, { color: cfg.border }]}>{cfg.label}</Text>
          <Text style={[styles.aiTag, { color: textColor }]}>· AI</Text>
        </View>
        <Ionicons
          name={expanded ? 'chevron-up' : 'chevron-down'}
          size={13}
          color={textColor}
        />
      </View>

      <Text style={[styles.contextText, { color: textColor }]} numberOfLines={expanded ? undefined : 2}>
        {result.context}
      </Text>

      {expanded && !!result.detail && (
        <Text style={[styles.detailText, { color: textColor }]}>{result.detail}</Text>
      )}

      {expanded && (
        <Text style={[styles.footer, { color: textColor }]}>
          Generated by Groq AI · Not a definitive fact-check. Use your own judgement.
        </Text>
      )}
    </TouchableOpacity>
  );
});

const styles = StyleSheet.create({
  card: {
    marginHorizontal: 12,
    marginTop: 4,
    marginBottom: 2,
    borderRadius: 8,
    borderLeftWidth: 3,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 5,
  },
  rowLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  label: {
    fontSize: 10,
    fontWeight: '700',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  aiTag: {
    fontSize: 10,
    fontWeight: '500',
    opacity: 0.8,
  },
  contextText: {
    fontSize: 13,
    lineHeight: 18,
  },
  detailText: {
    fontSize: 12,
    lineHeight: 17,
    marginTop: 7,
    opacity: 0.85,
  },
  footer: {
    fontSize: 10,
    marginTop: 8,
    opacity: 0.55,
    fontStyle: 'italic',
  },
});
