export const MAJORS: string[] = [
  // Computer & Technology
  'Computer Science',
  'Software Engineering',
  'Computer Engineering',
  'Information Technology',
  'Cybersecurity',
  'Data Science',
  'Artificial Intelligence',
  'Machine Learning',
  'Information Systems',
  'Web Development',
  'Game Design',
  'Human-Computer Interaction',
  // Engineering
  'Electrical Engineering',
  'Mechanical Engineering',
  'Civil Engineering',
  'Chemical Engineering',
  'Biomedical Engineering',
  'Aerospace Engineering',
  'Industrial Engineering',
  'Environmental Engineering',
  'Materials Science & Engineering',
  'Nuclear Engineering',
  'Systems Engineering',
  // Natural Sciences
  'Biology',
  'Biochemistry',
  'Chemistry',
  'Physics',
  'Mathematics',
  'Statistics',
  'Neuroscience',
  'Environmental Science',
  'Geology',
  'Astronomy',
  'Marine Biology',
  'Ecology',
  'Genetics',
  'Microbiology',
  // Business
  'Business Administration',
  'Finance',
  'Accounting',
  'Economics',
  'Marketing',
  'Management',
  'Entrepreneurship',
  'International Business',
  'Supply Chain Management',
  'Human Resources Management',
  'Real Estate',
  'Business Analytics',
  // Health & Medicine
  'Pre-Medicine',
  'Nursing',
  'Public Health',
  'Pharmacy',
  'Kinesiology',
  'Nutrition & Dietetics',
  'Occupational Therapy',
  'Physical Therapy',
  'Dental Hygiene',
  'Medical Laboratory Science',
  'Radiologic Technology',
  'Health Informatics',
  // Social Sciences
  'Psychology',
  'Sociology',
  'Political Science',
  'Anthropology',
  'International Relations',
  'Criminal Justice',
  'Social Work',
  'Geography',
  'Urban Planning',
  'Public Policy',
  'Gender Studies',
  // Humanities
  'English',
  'History',
  'Philosophy',
  'Linguistics',
  'Religious Studies',
  'Classics',
  'Comparative Literature',
  'Cultural Studies',
  // Communications & Media
  'Communications',
  'Journalism',
  'Public Relations',
  'Advertising',
  'Media Studies',
  'Film Studies',
  'Digital Media',
  'Broadcasting',
  // Arts & Design
  'Fine Arts',
  'Graphic Design',
  'Architecture',
  'Interior Design',
  'Fashion Design',
  'Industrial Design',
  'Photography',
  'Animation',
  'Music',
  'Music Performance',
  'Music Production',
  'Theater',
  'Dance',
  // Education
  'Education',
  'Early Childhood Education',
  'Special Education',
  'Secondary Education',
  'Physical Education',
  'Curriculum & Instruction',
  // Law
  'Pre-Law',
  'Legal Studies',
  'Paralegal Studies',
  // Other
  'Library Science',
  'Hospitality Management',
  'Tourism & Travel',
  'Culinary Arts',
  'Agriculture',
  'Veterinary Science',
  'Forensic Science',
  'Aviation',
  'Military Science',
  'Undeclared',
];

export function searchMajors(query: string): string[] {
  if (!query.trim()) return [];
  const q = query.toLowerCase();
  return MAJORS.filter(m => m.toLowerCase().includes(q)).slice(0, 15);
}
