import GH_UNIVERSITIES_DATA from './gh_universities.json';

// Combine the raw names for the legacy local list fallback
const GH_NAMES = Array.from(new Set(GH_UNIVERSITIES_DATA.map(u => u.name)));

export const UNIVERSITIES: string[] = [
  ...GH_NAMES,
  // United States
  'Harvard University',
  'Massachusetts Institute of Technology',
  'Stanford University',
  'Yale University',
  'Princeton University',
  'Columbia University',
  'University of Pennsylvania',
  'Cornell University',
  'Dartmouth College',
  'Brown University',
  'Duke University',
  'Northwestern University',
  'Johns Hopkins University',
  'Vanderbilt University',
  'Rice University',
  'Washington University in St. Louis',
  'Emory University',
  'Notre Dame University',
  'Georgetown University',
  'Carnegie Mellon University',
  'University of Southern California',
  'New York University',
  'Tufts University',
  'Boston University',
  'Northeastern University',
  'Boston College',
  'Fordham University',
  'George Washington University',
  'American University',
  'University of Miami',
  'Tulane University',
  'Wake Forest University',
  'Case Western Reserve University',
  'Lehigh University',
  'University of Rochester',
  'Rensselaer Polytechnic Institute',
  'Syracuse University',
  'Stevens Institute of Technology',
  'Drexel University',
  'Temple University',
  'Villanova University',
  'University of Delaware',
  'University of Maryland',
  'University of Virginia',
  'University of North Carolina at Chapel Hill',
  'University of Michigan',
  'University of California, Los Angeles',
  'University of California, Berkeley',
  'University of California, San Diego',
  'University of California, Davis',
  'University of California, Santa Barbara',
  'University of California, Irvine',
  'University of California, Santa Cruz',
  'University of California, Riverside',
  'University of California, Merced',
  'University of Washington',
  'University of Oregon',
  'Oregon State University',
  'University of Colorado Boulder',
  'Colorado State University',
  'University of Utah',
  'University of Arizona',
  'Arizona State University',
  'University of Nevada, Las Vegas',
  'University of Nevada, Reno',
  'University of New Mexico',
  'Texas A&M University',
  'University of Texas at Austin',
  'University of Texas at Dallas',
  'University of Texas at San Antonio',
  'University of Houston',
  'Rice University',
  'Baylor University',
  'Texas Christian University',
  'Texas Tech University',
  'Southern Methodist University',
  'University of Oklahoma',
  'Oklahoma State University',
  'University of Kansas',
  'Kansas State University',
  'University of Missouri',
  'University of Nebraska',
  'Iowa State University',
  'University of Iowa',
  'University of Minnesota',
  'University of Wisconsin-Madison',
  'University of Wisconsin-Milwaukee',
  'Michigan State University',
  'Wayne State University',
  'University of Illinois at Urbana-Champaign',
  'University of Illinois at Chicago',
  'Illinois Institute of Technology',
  'DePaul University',
  'Loyola University Chicago',
  'Northwestern University',
  'University of Chicago',
  'Indiana University',
  'Purdue University',
  'University of Notre Dame',
  'Butler University',
  'Ohio State University',
  'University of Cincinnati',
  'Case Western Reserve University',
  'University of Dayton',
  'Miami University',
  'Kent State University',
  'Ohio University',
  'University of Kentucky',
  'University of Louisville',
  'Vanderbilt University',
  'University of Tennessee',
  'Tennessee State University',
  'Auburn University',
  'University of Alabama',
  'University of Alabama at Birmingham',
  'University of Mississippi',
  'Mississippi State University',
  'Louisiana State University',
  'Tulane University',
  'University of New Orleans',
  'University of Arkansas',
  'University of Florida',
  'Florida State University',
  'University of Central Florida',
  'University of South Florida',
  'Florida International University',
  'Florida Atlantic University',
  'University of Georgia',
  'Georgia Tech',
  'Emory University',
  'Georgia State University',
  'Clemson University',
  'University of South Carolina',
  'College of Charleston',
  'University of North Carolina at Charlotte',
  'North Carolina State University',
  'Wake Forest University',
  'East Carolina University',
  'Virginia Tech',
  'George Mason University',
  'James Madison University',
  'Old Dominion University',
  'William & Mary',
  'Howard University',
  'American University',
  'Catholic University of America',
  'West Virginia University',
  'University of Pittsburgh',
  'Penn State University',
  'Temple University',
  'Drexel University',
  'La Salle University',
  'Rutgers University',
  'Seton Hall University',
  'Montclair State University',
  'New Jersey Institute of Technology',
  'Princeton University',
  'University of Connecticut',
  'Quinnipiac University',
  'Fairfield University',
  'Sacred Heart University',
  'University of Rhode Island',
  'Bryant University',
  'Providence College',
  'Brown University',
  'University of Massachusetts Amherst',
  'University of Massachusetts Boston',
  'Northeastern University',
  'Boston University',
  'Boston College',
  'Tufts University',
  'Brandeis University',
  'Worcester Polytechnic Institute',
  'University of New Hampshire',
  'Dartmouth College',
  'University of Vermont',
  'Middlebury College',
  'University of Maine',
  'Bowdoin College',
  'Colby College',
  'Bates College',
  // Canada
  'University of Toronto',
  'McGill University',
  'University of British Columbia',
  'University of Alberta',
  'McMaster University',
  'University of Waterloo',
  'Queens University',
  'Western University',
  'University of Calgary',
  'University of Ottawa',
  'York University',
  'Dalhousie University',
  'Simon Fraser University',
  'University of Victoria',
  'University of Manitoba',
  'University of Saskatchewan',
  'Ryerson University',
  'Concordia University',
  'Université de Montréal',
  'Université Laval',
  'Carleton University',
  // United Kingdom
  'University of Oxford',
  'University of Cambridge',
  'Imperial College London',
  'University College London',
  'London School of Economics',
  'University of Edinburgh',
  'University of Manchester',
  'Kings College London',
  'University of Bristol',
  'University of Warwick',
  'University of Glasgow',
  'University of Birmingham',
  'University of Leeds',
  'University of Sheffield',
  'University of Nottingham',
  'University of Southampton',
  'University of Liverpool',
  'Newcastle University',
  'Cardiff University',
  'Queen Mary University of London',
  'Durham University',
  'University of Bath',
  'University of Exeter',
  'University of Surrey',
  'Lancaster University',
  'University of York',
  'University of Leicester',
  'Loughborough University',
  'University of Aberdeen',
  'University of Dundee',
  'Heriot-Watt University',
  'University of Strathclyde',
  'Queens University Belfast',
  'University of Ulster',
  // Australia
  'University of Melbourne',
  'Australian National University',
  'University of Sydney',
  'University of Queensland',
  'University of New South Wales',
  'Monash University',
  'University of Western Australia',
  'University of Adelaide',
  'Queensland University of Technology',
  'RMIT University',
  'University of Technology Sydney',
  'Deakin University',
  'Flinders University',
  'Griffith University',
  'Macquarie University',
  'Swinburne University of Technology',
  'James Cook University',
  'La Trobe University',
  'Curtin University',
  'Edith Cowan University',
  // Europe
  'ETH Zurich',
  'EPFL',
  'University of Amsterdam',
  'Delft University of Technology',
  'Eindhoven University of Technology',
  'Utrecht University',
  'Leiden University',
  'KU Leuven',
  'Ghent University',
  'Technical University of Munich',
  'Ludwig Maximilian University of Munich',
  'Heidelberg University',
  'Humboldt University of Berlin',
  'Free University of Berlin',
  'RWTH Aachen University',
  'University of Hamburg',
  'University of Frankfurt',
  'University of Cologne',
  'Sorbonne University',
  'Sciences Po',
  'Ecole Polytechnique',
  'HEC Paris',
  'University of Paris',
  'Stockholm University',
  'KTH Royal Institute of Technology',
  'Lund University',
  'Uppsala University',
  'University of Copenhagen',
  'Aarhus University',
  'University of Oslo',
  'University of Bergen',
  'University of Helsinki',
  'Aalto University',
  'University of Vienna',
  'Technical University of Vienna',
  'University of Zurich',
  'University of Bern',
  'University of Geneva',
  'University of Basel',
  'Trinity College Dublin',
  'University College Dublin',
  'University College Cork',
  'University of Galway',
  'Bocconi University',
  'University of Bologna',
  'Sapienza University of Rome',
  'Polytechnic University of Milan',
  'University of Milan',
  'University of Florence',
  'University of Padua',
  'Complutense University of Madrid',
  'Universidad Autonoma de Madrid',
  'University of Barcelona',
  'University of Lisbon',
  'University of Porto',
  // Asia
  'University of Tokyo',
  'Kyoto University',
  'Osaka University',
  'Tokyo Institute of Technology',
  'Tohoku University',
  'Nagoya University',
  'National University of Singapore',
  'Nanyang Technological University',
  'Seoul National University',
  'Korea Advanced Institute of Science and Technology',
  'Yonsei University',
  'Korea University',
  'Sungkyunkwan University',
  'Pohang University of Science and Technology',
  'Peking University',
  'Tsinghua University',
  'Fudan University',
  'Shanghai Jiao Tong University',
  'Zhejiang University',
  'University of Science and Technology of China',
  'Nanjing University',
  'Sun Yat-sen University',
  'Wuhan University',
  'Xi\'an Jiaotong University',
  'Harbin Institute of Technology',
  'University of Hong Kong',
  'Chinese University of Hong Kong',
  'Hong Kong University of Science and Technology',
  'Hong Kong Polytechnic University',
  'City University of Hong Kong',
  'National Taiwan University',
  'Indian Institute of Technology Bombay',
  'Indian Institute of Technology Delhi',
  'Indian Institute of Technology Madras',
  'Indian Institute of Technology Kanpur',
  'Indian Institute of Technology Kharagpur',
  'Indian Institute of Science',
  'University of Delhi',
  'Jawaharlal Nehru University',
  'University of Mumbai',
  'University of Calcutta',
  'University of Hyderabad',
  'University of Malaya',
  'Universiti Putra Malaysia',
  'Universiti Teknologi Malaysia',
  'Universiti Kebangsaan Malaysia',
  'Chulalongkorn University',
  'Mahidol University',
  'University of the Philippines',
  'Ateneo de Manila University',
  'De La Salle University',
  'University of Indonesia',
  'Gadjah Mada University',
  'Bandung Institute of Technology',
  // Middle East & Africa
  'American University of Beirut',
  'University of Cape Town',
  'Stellenbosch University',
  'University of Pretoria',
  'University of Witwatersrand',
  'University of Nairobi',
  'American University in Cairo',
  'Cairo University',
  'University of Lagos',
  'University of Ghana',
  'King Abdulaziz University',
  'King Fahd University of Petroleum and Minerals',
  'King Abdullah University of Science and Technology',
  'American University of Sharjah',
  'American University in Dubai',
  'Hebrew University of Jerusalem',
  'Tel Aviv University',
  'Technion',
  // Latin America
  'University of São Paulo',
  'University of Campinas',
  'Pontifical Catholic University of Chile',
  'University of Chile',
  'National Autonomous University of Mexico',
  'Tecnológico de Monterrey',
  'Pontifical Catholic University of Peru',
  'University of Buenos Aires',
  'University of the Andes',
  'National University of Colombia',
];

export async function searchUniversities(query: string): Promise<string[]> {
  if (!query.trim() || query.length < 2) return [];

  const q = query.toLowerCase();

  // 1. Check local Ghanaian list first (Instant/Offline)
  const localGhanaMatches = GH_NAMES.filter(u => u.toLowerCase().includes(q));
  
  if (localGhanaMatches.length > 0) {
    // Return local results immediately
    return localGhanaMatches.slice(0, 15);
  }

  // 2. Try global API if no local matches
  try {
    const res = await fetch(
      `https://universities.hipolabs.com/search?name=${encodeURIComponent(query)}`
    );
    if (!res.ok) throw new Error('API request failed');
    const data = await res.json();
    
    if (Array.isArray(data) && data.length > 0) {
      // Return unique names
      const apiResults = Array.from(new Set(data.map((u: any) => u.name)));
      return apiResults.slice(0, 25);
    }
  } catch (error) {
    console.warn('University API failed, falling back to full local list:', error);
  }

  // 3. Fallback to the full static list (includes global big names)
  return UNIVERSITIES.filter(u => u.toLowerCase().includes(q)).slice(0, 20);
}

